<template>
  <Modal
    title="사용자 추가"
    :click-to-close="true"
    :esc-to-close="true"
    :display-directive="'show'"
    :width="480"
    :height="516"
    confirmBtnMsg="생성"
    @before-open="beforeOpen"
    @cancel="onCancel"
    @confirm="onConfirm"
  >
    <template v-slot:body>
      <div class="form form-vertical">
        <div class="form-body">
          <div class="form-item">
            <label for="" class="form-label">
              이메일
              <span class="required">*</span>
            </label>
            <div class="form-detail">
              <div class="search-input">
                <label class="hidden-text" for="service-add-input-email">
                  label
                </label>
                <input
                  id="service-add-input-email"
                  class="text-input text-input-lg"
                  placeholder="이메일"
                  v-model="params.email"
                />
                <button
                  class="search-input-action-button button button-neutral-ghost button-sm"
                  type="button"
                  @click="resetInputValue('email')"
                >
                  <span class="hidden-text">이메일 지우기</span>
                  <svg-icon class="button-icon" name="close"></svg-icon>
                </button>
              </div>
              <div
                v-if="emailInpErrorMsg"
                class="notification notification-sm notification-error"
              >
                <svg-icon class="notification-icon" name="error"></svg-icon>
                <p class="notification-detail">{{ emailInpErrorMsg }}</p>
              </div>
            </div>
          </div>
          <div class="form-item">
            <label for="" class="form-label"> 이름표시 </label>
            <div class="form-detail flex flex-col">
              <div class="search-input">
                <label class="hidden-text" for="service-add-input-name">
                  label
                </label>
                <input
                  id="service-add-input-name"
                  class="text-input text-input-lg"
                  placeholder="이름"
                  v-model="params.displayName"
                />
                <button
                  class="search-input-action-button button button-neutral-ghost button-sm"
                  type="button"
                  @click="resetInputValue('displayName')"
                >
                  <span class="hidden-text">이름표시 지우기</span>
                  <svg-icon class="button-icon" name="close"></svg-icon>
                </button>
              </div>
            </div>
          </div>
          <div class="form-item">
            <label class="form-label" for="service-add-description">
              설명
            </label>
            <div class="form-detail">
              <textarea
                id="service-add-description"
                class="textarea h-28"
                placeholder="설명을 입력하세요."
                v-model="params.description"
              ></textarea>
            </div>
          </div>
          <div class="form-item">
            <label for="" class="form-label">비밀번호</label>
            <div class="form-detail gap-2">
              <div class="radio-group">
                <div class="radio">
                  <input
                    type="radio"
                    id="radiosm"
                    class="radio-input"
                    name="radio2"
                    :value="true"
                    v-model="isAutoGeneratedPwd"
                  />
                  <label for="radiosm" class="radio-label">
                    비밀번호 자동생성
                  </label>
                </div>
                <div class="radio">
                  <input
                    type="radio"
                    id="radiosm3"
                    class="radio-input"
                    name="radio2"
                    :value="false"
                    v-model="isAutoGeneratedPwd"
                  />
                  <label for="radiosm3" class="radio-label"
                    >비밀번호 직접생성
                  </label>
                </div>
              </div>
              <!-- 비밀번호 자동생성 -->
              <div v-if="isAutoGeneratedPwd" class="text-input-group">
                <div class="v-group w-full">
                  <div class="search-input">
                    <label class="hidden-text" for="service-add-input-password">
                      label
                    </label>
                    <input
                      id="service-add-input-password"
                      :type="isShowPwdStatus.password ? 'input' : 'password'"
                      class="text-input text-input-lg"
                      v-model="params.password"
                    />
                    <button
                      class="search-input-action-button button button-neutral-ghost button-sm"
                      type="button"
                      @click="setShowPwdStatus('password')"
                    >
                      <span class="hidden-text"
                        >비밀번호
                        {{ isShowPwdStatus.password ? "표시" : "숨김" }}</span
                      >
                      <svg-icon
                        class="button-icon"
                        :name="
                          getPwdIconName({
                            isVisible: isShowPwdStatus.password,
                          })
                        "
                      ></svg-icon>
                    </button>
                  </div>
                </div>
                <button
                  class="button button-neutral-stroke button-xl"
                  @click="resetRandomPwd"
                >
                  <span class="hidden-text"></span>
                  <svg-icon class="icons button-icon" name="reset"></svg-icon>
                </button>
                <button
                  class="button button-neutral-stroke button-xl"
                  @click="pwdCopyBtnClicked"
                >
                  <span class="hidden-text"></span>
                  <svg-icon class="icons button-icon" name="copy"></svg-icon>
                </button>
              </div>
              <!-- 비밀번호 직접생성 -->
              <div v-if="!isAutoGeneratedPwd" class="search-input">
                <label
                  class="hidden-text"
                  for="service-add-input-password-direct"
                >
                  label
                </label>
                <input
                  id="service-add-input-password-direct"
                  :type="isShowPwdStatus.password ? 'input' : 'password'"
                  class="text-input text-input-lg"
                  v-model="params.password"
                />
                <button
                  class="search-input-action-button button button-neutral-ghost button-sm"
                  type="button"
                  @click="setShowPwdStatus('password')"
                >
                  <span class="hidden-text"
                    >비밀번호
                    {{ isShowPwdStatus.password ? "표시" : "숨김" }}</span
                  >
                  <svg-icon
                    class="button-icon"
                    :name="
                      getPwdIconName({ isVisible: isShowPwdStatus.password })
                    "
                  ></svg-icon>
                </button>
              </div>
              <div
                v-if="pwdInpErrorMsg"
                class="notification notification-sm notification-error"
              >
                <svg-icon class="notification-icon" name="error"></svg-icon>
                <p class="notification-detail">
                  {{ pwdInpErrorMsg }}
                </p>
              </div>
            </div>
          </div>
          <!-- 비밀번호 직접생성 선택시 노출 -->
          <div v-if="!isAutoGeneratedPwd" class="form-item">
            <label for="" class="form-label">비밀번호 확인</label>
            <div class="form-detail">
              <div class="search-input">
                <label
                  class="hidden-text"
                  for="service-add-input-password-check"
                  >label
                </label>
                <input
                  id="service-add-input-password-check"
                  :type="isShowPwdStatus.confirmPassword ? 'input' : 'password'"
                  class="text-input text-input-lg"
                  v-model="params.confirmPassword"
                />
                <button
                  class="search-input-action-button button button-neutral-ghost button-sm"
                  type="button"
                  @click="setShowPwdStatus('confirmPassword')"
                >
                  <span class="hidden-text"
                    >비밀번호
                    {{
                      isShowPwdStatus.confirmPassword ? "표시" : "숨김"
                    }}</span
                  >
                  <svg-icon
                    class="button-icon"
                    :name="
                      getPwdIconName({
                        isVisible: isShowPwdStatus.confirmPassword,
                      })
                    "
                  ></svg-icon>
                </button>
              </div>
              <div
                v-if="confirmPwdInpErrorMsg"
                class="notification notification-sm notification-error"
              >
                <svg-icon class="notification-icon" name="error"></svg-icon>
                <p class="notification-detail">{{ confirmPwdInpErrorMsg }}</p>
              </div>
            </div>
          </div>
          <div class="form-item">
            <label for="" class="form-label">관리자</label>
            <div class="form-detail">
              <div class="switch">
                <input
                  type="checkbox"
                  id="manager-sw"
                  class="switch-input"
                  v-model="params.isAdmin"
                />
                <label for="manager-sw" class="switch-label">
                  <div class="switch-control"></div>
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { useUserStore } from "~/store/user/userStore";
import { useCommonUtils } from "@/composables/commonUtils";
import type { AddUser } from "~/type/user";
import Modal from "@extends/modal/Modal.vue";

import _ from "lodash";
import $constants from "@/utils/constant";

const { getPwdIconName } = useCommonUtils();
const userStore = useUserStore();
const { getRandomPwd, checkDuplicateEmail, checkDuplicateName, addUser } =
  userStore;
const defaultAddUser = userStore.defaultAddUser;

const emit = defineEmits<{
  (e: "close"): void;
  (e: "userAddedSuccess"): void;
}>();

const params: Ref<AddUser> = ref(defaultAddUser);
const isAutoGeneratedPwd: Ref<boolean> = ref(true);
const isShowPwdStatus: Ref<{ [key: string]: boolean }> = ref({
  password: false,
  confirmPassword: false,
});
const emailInpErrorMsg: Ref<string> = ref("");
const pwdInpErrorMsg: Ref<string> = ref("");
const confirmPwdInpErrorMsg: Ref<string> = ref("");

watch(isAutoGeneratedPwd, (value: boolean) => {
  resetInputValue("password");
  resetInputValue("confirmPassword");
  isShowPwdStatus.value.password = false;
  isShowPwdStatus.value.confirmPassword = false;
  pwdInpErrorMsg.value = "";
  confirmPwdInpErrorMsg.value = "";
  if (value) {
    resetRandomPwd();
  }
});

const beforeOpen = () => {
  params.value = _.cloneDeep(defaultAddUser);
  if (isAutoGeneratedPwd.value) {
    resetRandomPwd();
  } else {
    isAutoGeneratedPwd.value = true;
  }
};

const resetInputValue = (key: keyof AddUser) => {
  if (typeof params.value[key] === "string") {
    params.value[key] = "";
  }
};

const setShowPwdStatus = (id: string) => {
  isShowPwdStatus.value[id] = !isShowPwdStatus.value[id];
};

const resetRandomPwd = async () => {
  params.value.password = await getRandomPwd();
  params.value.confirmPassword = params.value.password;
};

const pwdCopyBtnClicked = async () => {
  try {
    await navigator.clipboard.writeText(params.value.password);
    alert("비밀번호가 복사되었습니다.");
  } catch (err) {
    alert("비밀번호 복사에 실패했습니다. 다시 시도해 주세요.");
  }
};

const onCancel = () => {
  emit("close");
};

const onConfirm = async () => {
  // name 값은 email 의 id 값과 같음
  params.value.name = _.first(_.split(params.value.email, "@")) || "";

  // 비밀번호 자동생성일 경우에는 confirmPassword 값은 password 와 같음.
  if (isAutoGeneratedPwd.value) {
    params.value.confirmPassword = params.value.password;
  }

  // email and password validation check
  const isEmailValid = await checkEmailValidation();
  const isPwdValid = checkPwdValidation();
  if (!isEmailValid || !isPwdValid) return;

  // 사용자 추가
  await addUser(params.value).then((data) => {
    if (_.isEmpty(data)) {
      alert("사용자 생성 실패했습니다. 잠시 후 다시 시도해주세요.");
    } else {
      alert("사용자 생성이 완료되었습니다.");
      emit("close");
      emit("userAddedSuccess");
    }
  });
};

const checkEmailValidation = async () => {
  const { email, name } = params.value;
  let isValidation = true;

  if (_.isEmpty(email)) {
    // 이메일 값 입력 여부 체크
    emailInpErrorMsg.value = $constants.LOGIN.EMAIL.INPUT_ERROR_MSG;
    isValidation = false;
  } else if (!$constants.LOGIN.EMAIL.REGEX.test(email)) {
    // 이메일 형식 체크
    emailInpErrorMsg.value = $constants.LOGIN.EMAIL.REGEX_ERROR_MSG;
    isValidation = false;
  } else if (await checkDuplicateEmail(email)) {
    // 이메일 중복 체크
    emailInpErrorMsg.value = $constants.LOGIN.EMAIL.DUPLICATE_ERROR_MSG;
    isValidation = false;
  } else if (await checkDuplicateName(name)) {
    // 이메일 아이디 중복 체크, name 으로 중복체크함
    emailInpErrorMsg.value = $constants.LOGIN.EMAIL.DUPLICATE_ID_ERROR_MSG;
    isValidation = false;
  }

  if (isValidation) emailInpErrorMsg.value = "";
  return isValidation;
};

const checkPwdValidation = () => {
  const { password, confirmPassword } = params.value;
  let isValidation = true;

  if (_.isEmpty(password)) {
    // password 값 입력여부 체크
    pwdInpErrorMsg.value = $constants.LOGIN.PASSWORD.INPUT_ERROR_MSG;
    isValidation = false;
  } else if (!$constants.LOGIN.PASSWORD.REGEX.test(password)) {
    // 비밀번호 자동생성일 경우에도 비밀번호 수정이 가능하기 때문에 체크해준다.
    // password 형식 체크
    pwdInpErrorMsg.value = $constants.LOGIN.PASSWORD.REGEX_ERROR_MSG;
    isValidation = false;
  } else {
    pwdInpErrorMsg.value = "";
  }

  if (_.isEmpty(confirmPassword)) {
    // confirmPassword 값 입력여부 체크
    confirmPwdInpErrorMsg.value = $constants.LOGIN.PASSWORD.INPUT_ERROR_MSG;
    isValidation = false;
  } else if (password !== confirmPassword) {
    // password 와 confirmPassword 가 일치하는지 체크
    confirmPwdInpErrorMsg.value = $constants.LOGIN.PASSWORD.MATCH_ERROR_MSG;
    isValidation = false;
  } else {
    confirmPwdInpErrorMsg.value = "";
  }

  return isValidation;
};
</script>

<style></style>
