spring:
  application:
    name: ovp
  profiles:
    active: local
  web:
    locale: ko
    resources:
      chain:
        compressed: true
        cache: true
      add-mappings: true

  output:
    ansi:
      enabled: detect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jpa:
    hibernate:
      ddl-auto: validate

  primary:
    datasource:
      hikari:
        idle-timeout: 10000
        maximum-pool-size: 10
        minimum-idle: 5
        pool-name: BaseHikariPool
        jdbc-url: jdbc:postgresql://192.168.105.26:5432/postgres?currentSchema=ovp
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    hibernate:
      property:
        "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
        "[hibernate.show_sql]": true
        "[hibernate.format_sql]": true
        "[hibernate.hbm2ddl.auto]": none
        "[hibernate.cache.use_second_level_cache]": false
        "[hibernate.cache.use_query_cache]": false
        "[hibernate.globally_quoted_identifiers]": true
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    com:
      mobigen: debug

server:
  port: 8080
  servlet:
    session:
      timeout: 7200
      cookie:
        name: ovp-session-id
    encoding:
      charset: UTF-8
    context-path: /
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
  error:
    whitelabel:
      enabled: false
    path: /error

i18n:
  basenames: i18n/messages, i18n/exception, i18n/validation

http-client-configuration:
  max-total: 300
  default-max-per-route: 50
  default-keep-alive-duration: -1
  connection-reqeust-timeout: 3000
  connection-timeout: 3000
  socket-timeout: -1
  idle-timeout: 60

#sentry:
#  dsn: https://c10f0211c0bb41af973f1f5ebf7fda60@o924939.ingest.sentry.io/6044951
#  traces-sample-rate: 1
#  logging:
#    enabled: off

# 사용자 정의 설정들
properties:
  framework:
    security:
      ignores: /css/**, /fonts/**, /img/**, /js/**, /favicon.ico
      permit-alls: /h2-console/**, /error, /test, /api/auth/iag/**, /api/auth/login/**, /api/sample/** # /**, /h2-console/**,
      redirect-url: /
      iframe-option: disable #disable, same-origin, deny
      csrf: false
      cors:
        pattern: /** #/auth/**
        allowed-origins: http://localhost:3300/ #"*" #http://server-name:port
        allowed-methods: "*" #PUT,DELETE,GET,POST ...
        allowed-headers: "*" #Context-Type, ...
        allow-credentials: true
      same-site: Lax #None, Lax, Strict
    token:
      access-token: accessToken
      refresh-token: refreshToken
      secret: jwt-secrect-b-iris # Keycloak "HS256" 알고리즘 secret 값
    route:
      locales: ko,en,zh,ja
    auth:
      rsa-enabled: true
    test:
      username: admin
      password: admin
  ovp:
    open-metadata-url: http://192.168.105.26:8585/api/v1
